### ISSUE TITLE
Hungarian language

### ISSUE THREAD

**Issue by MDylan** [searchwork/nwt-reading-contrib#1]
Hi!

I have made the hungarian translation for this app.
Language file attached.

Best regards,
David
[hu.zip](https://github.com/searchwork/nwt-reading-contrib/files/6840289/hu.zip)

**Comment by krdsrl** [comment]
Hi!

Could you please append this translation, it would be nice. :D

Thanks,
Raul

**Comment by wfleischer** [comment]
Sorry for the very late follow up! The Hungarian language is now available and is rolled out.
